// Seed data for faculties and departments
// This data is based on the user's requirements

const facultiesData = [
  { name: "Faculty of Science", description: "Department of Sciences", icon: "🔬" },
  { name: "Faculty of Engineering", description: "Department of Engineering", icon: "🏗" },
  { name: "Faculty of Business & Management Sciences", description: "Department of Business", icon: "💼" },
  { name: "Faculty of Arts & Humanities", description: "Department of Arts", icon: "🎨" },
  { name: "Faculty of Social Sciences", description: "Department of Social Sciences", icon: "🌍" },
  { name: "Faculty of Health Sciences", description: "Department of Health Sciences", icon: "🏥" },
  { name: "Faculty of Law", description: "Department of Law", icon: "⚖" },
  { name: "Faculty of Agriculture", description: "Department of Agriculture", icon: "🌾" },
  { name: "Faculty of Education", description: "Department of Education", icon: "🏛" },
  { name: "Faculty of Environmental Sciences", description: "Department of Environmental Sciences", icon: "🏗" },
  { name: "Faculty of Information & Digital Technologies", description: "Department of IT", icon: "💻" },
  { name: "Faculty of Transport & Logistics", description: "Department of Transport", icon: "🚢" },
  { name: "Faculty of Creative & Media Technologies", description: "Department of Creative Arts", icon: "🎭" },
  { name: "Faculty of Advanced Research & Innovation", description: "Department of Research", icon: "🔬" },
  { name: "Faculty of Professional Studies", description: "Department of Professional Studies", icon: "📊" }
];

const departmentsData = [
  // Faculty of Science
  { facultyName: "Faculty of Science", name: "Department of Computer Science" },
  { facultyName: "Faculty of Science", name: "Department of Software Engineering" },
  { facultyName: "Faculty of Science", name: "Department of Information Systems" },
  { facultyName: "Faculty of Science", name: "Department of Cybersecurity" },
  { facultyName: "Faculty of Science", name: "Department of Artificial Intelligence" },
  { facultyName: "Faculty of Science", name: "Department of Data Science" },
  { facultyName: "Faculty of Science", name: "Department of Mathematics" },
  { facultyName: "Faculty of Science", name: "Department of Applied Mathematics" },
  { facultyName: "Faculty of Science", name: "Department of Statistics" },
  { facultyName: "Faculty of Science", name: "Department of Actuarial Science" },
  { facultyName: "Faculty of Science", name: "Department of Physics" },
  { facultyName: "Faculty of Science", name: "Department of Applied Physics" },
  { facultyName: "Faculty of Science", name: "Department of Medical Physics" },
  { facultyName: "Faculty of Science", name: "Department of Chemistry" },
  { facultyName: "Faculty of Science", name: "Department of Industrial Chemistry" },
  { facultyName: "Faculty of Science", name: "Department of Biochemistry" },
  { facultyName: "Faculty of Science", name: "Department of Biology" },
  { facultyName: "Faculty of Science", name: "Department of Microbiology" },
  { facultyName: "Faculty of Science", name: "Department of Biotechnology" },
  { facultyName: "Faculty of Science", name: "Department of Environmental Science" },

  // Faculty of Engineering
  { facultyName: "Faculty of Engineering", name: "Department of Mechanical Engineering" },
  { facultyName: "Faculty of Engineering", name: "Department of Mechatronics Engineering" },
  { facultyName: "Faculty of Engineering", name: "Department of Automotive Engineering" },
  { facultyName: "Faculty of Engineering", name: "Department of Civil Engineering" },
  { facultyName: "Faculty of Engineering", name: "Department of Structural Engineering" },
  { facultyName: "Faculty of Engineering", name: "Department of Building Engineering" },
  { facultyName: "Faculty of Engineering", name: "Department of Electrical Engineering" },
  { facultyName: "Faculty of Engineering", name: "Department of Electronics Engineering" },
  { facultyName: "Faculty of Engineering", name: "Department of Computer Engineering" },
  { facultyName: "Faculty of Engineering", name: "Department of Telecommunications Engineering" },
  { facultyName: "Faculty of Engineering", name: "Department of Chemical Engineering" },
  { facultyName: "Faculty of Engineering", name: "Department of Petroleum Engineering" },
  { facultyName: "Faculty of Engineering", name: "Department of Gas Engineering" },
  { facultyName: "Faculty of Engineering", name: "Department of Marine Engineering" },
  { facultyName: "Faculty of Engineering", name: "Department of Aerospace Engineering" },
  { facultyName: "Faculty of Engineering", name: "Department of Agricultural Engineering" },
  { facultyName: "Faculty of Engineering", name: "Department of Biomedical Engineering" },
  { facultyName: "Faculty of Engineering", name: "Department of Materials Engineering" },
  { facultyName: "Faculty of Engineering", name: "Department of Metallurgical Engineering" },
  { facultyName: "Faculty of Engineering", name: "Department of Industrial & Production Engineering" },

  // Faculty of Business & Management Sciences
  { facultyName: "Faculty of Business & Management Sciences", name: "Department of Business Administration" },
  { facultyName: "Faculty of Business & Management Sciences", name: "Department of Management Studies" },
  { facultyName: "Faculty of Business & Management Sciences", name: "Department of Human Resource Management" },
  { facultyName: "Faculty of Business & Management Sciences", name: "Department of Entrepreneurship" },
  { facultyName: "Faculty of Business & Management Sciences", name: "Department of Marketing" },
  { facultyName: "Faculty of Business & Management Sciences", name: "Department of International Business" },
  { facultyName: "Faculty of Business & Management Sciences", name: "Department of Accounting" },
  { facultyName: "Faculty of Business & Management Sciences", name: "Department of Finance" },
  { facultyName: "Faculty of Business & Management Sciences", name: "Department of Banking & Finance" },
  { facultyName: "Faculty of Business & Management Sciences", name: "Department of Insurance" },
  { facultyName: "Faculty of Business & Management Sciences", name: "Department of Economics" },
  { facultyName: "Faculty of Business & Management Sciences", name: "Department of Development Economics" },
  { facultyName: "Faculty of Business & Management Sciences", name: "Department of Public Administration" },
  { facultyName: "Faculty of Business & Management Sciences", name: "Department of Procurement & Supply Chain" },
  { facultyName: "Faculty of Business & Management Sciences", name: "Department of Logistics Management" },
  { facultyName: "Faculty of Business & Management Sciences", name: "Department of Project Management" },
  { facultyName: "Faculty of Business & Management Sciences", name: "Department of Taxation" },
  { facultyName: "Faculty of Business & Management Sciences", name: "Department of Real Estate Management" },
  { facultyName: "Faculty of Business & Management Sciences", name: "Department of Hospitality Management" },
  { facultyName: "Faculty of Business & Management Sciences", name: "Department of Tourism Management" },

  // Faculty of Arts & Humanities
  { facultyName: "Faculty of Arts & Humanities", name: "Department of English Language" },
  { facultyName: "Faculty of Arts & Humanities", name: "Department of English Literature" },
  { facultyName: "Faculty of Arts & Humanities", name: "Department of Linguistics" },
  { facultyName: "Faculty of Arts & Humanities", name: "Department of Creative Writing" },
  { facultyName: "Faculty of Arts & Humanities", name: "Department of History" },
  { facultyName: "Faculty of Arts & Humanities", name: "Department of International Studies" },
  { facultyName: "Faculty of Arts & Humanities", name: "Department of Philosophy" },
  { facultyName: "Faculty of Arts & Humanities", name: "Department of Religious Studies" },
  { facultyName: "Faculty of Arts & Humanities", name: "Department of Islamic Studies" },
  { facultyName: "Faculty of Arts & Humanities", name: "Department of Christian Studies" },
  { facultyName: "Faculty of Arts & Humanities", name: "Department of Theatre Arts" },
  { facultyName: "Faculty of Arts & Humanities", name: "Department of Performing Arts" },
  { facultyName: "Faculty of Arts & Humanities", name: "Department of Music" },
  { facultyName: "Faculty of Arts & Humanities", name: "Department of Fine Arts" },
  { facultyName: "Faculty of Arts & Humanities", name: "Department of Visual Arts" },
  { facultyName: "Faculty of Arts & Humanities", name: "Department of Graphic Design" },
  { facultyName: "Faculty of Arts & Humanities", name: "Department of Fashion Design" },
  { facultyName: "Faculty of Arts & Humanities", name: "Department of French" },
  { facultyName: "Faculty of Arts & Humanities", name: "Department of Spanish" },
  { facultyName: "Faculty of Arts & Humanities", name: "Department of Chinese Studies" },

  // Faculty of Social Sciences
  { facultyName: "Faculty of Social Sciences", name: "Department of Political Science" },
  { facultyName: "Faculty of Social Sciences", name: "Department of Public Policy" },
  { facultyName: "Faculty of Social Sciences", name: "Department of Sociology" },
  { facultyName: "Faculty of Social Sciences", name: "Department of Anthropology" },
  { facultyName: "Faculty of Social Sciences", name: "Department of Psychology" },
  { facultyName: "Faculty of Social Sciences", name: "Department of Criminology" },
  { facultyName: "Faculty of Social Sciences", name: "Department of Peace & Conflict Studies" },
  { facultyName: "Faculty of Social Sciences", name: "Department of Gender Studies" },
  { facultyName: "Faculty of Social Sciences", name: "Department of Geography" },
  { facultyName: "Faculty of Social Sciences", name: "Department of Urban & Regional Planning" },
  { facultyName: "Faculty of Social Sciences", name: "Department of Demography" },
  { facultyName: "Faculty of Social Sciences", name: "Department of Social Work" },
  { facultyName: "Faculty of Social Sciences", name: "Department of International Relations" },
  { facultyName: "Faculty of Social Sciences", name: "Department of Strategic Studies" },
  { facultyName: "Faculty of Social Sciences", name: "Department of Security Studies" },
  { facultyName: "Faculty of Social Sciences", name: "Department of Communication Studies" },
  { facultyName: "Faculty of Social Sciences", name: "Department of Media Studies" },
  { facultyName: "Faculty of Social Sciences", name: "Department of Journalism" },
  { facultyName: "Faculty of Social Sciences", name: "Department of Broadcasting" },
  { facultyName: "Faculty of Social Sciences", name: "Department of Development Studies" },

  // Faculty of Health Sciences
  { facultyName: "Faculty of Health Sciences", name: "Department of Medicine" },
  { facultyName: "Faculty of Health Sciences", name: "Department of Surgery" },
  { facultyName: "Faculty of Health Sciences", name: "Department of Nursing" },
  { facultyName: "Faculty of Health Sciences", name: "Department of Pharmacy" },
  { facultyName: "Faculty of Health Sciences", name: "Department of Pharmacology" },
  { facultyName: "Faculty of Health Sciences", name: "Department of Anatomy" },
  { facultyName: "Faculty of Health Sciences", name: "Department of Physiology" },
  { facultyName: "Faculty of Health Sciences", name: "Department of Medical Laboratory Science" },
  { facultyName: "Faculty of Health Sciences", name: "Department of Public Health" },
  { facultyName: "Faculty of Health Sciences", name: "Department of Environmental Health" },
  { facultyName: "Faculty of Health Sciences", name: "Department of Dentistry" },
  { facultyName: "Faculty of Health Sciences", name: "Department of Optometry" },
  { facultyName: "Faculty of Health Sciences", name: "Department of Physiotherapy" },
  { facultyName: "Faculty of Health Sciences", name: "Department of Radiography" },
  { facultyName: "Faculty of Health Sciences", name: "Department of Nutrition & Dietetics" },
  { facultyName: "Faculty of Health Sciences", name: "Department of Epidemiology" },
  { facultyName: "Faculty of Health Sciences", name: "Department of Health Information Management" },
  { facultyName: "Faculty of Health Sciences", name: "Department of Community Health" },
  { facultyName: "Faculty of Health Sciences", name: "Department of Veterinary Medicine" },
  { facultyName: "Faculty of Health Sciences", name: "Department of Biomedical Sciences" },

  // Faculty of Law
  { facultyName: "Faculty of Law", name: "Department of Public Law" },
  { facultyName: "Faculty of Law", name: "Department of Private Law" },
  { facultyName: "Faculty of Law", name: "Department of Commercial Law" },
  { facultyName: "Faculty of Law", name: "Department of International Law" },
  { facultyName: "Faculty of Law", name: "Department of Constitutional Law" },
  { facultyName: "Faculty of Law", name: "Department of Criminal Law" },
  { facultyName: "Faculty of Law", name: "Department of Property Law" },
  { facultyName: "Faculty of Law", name: "Department of Maritime Law" },
  { facultyName: "Faculty of Law", name: "Department of Environmental Law" },
  { facultyName: "Faculty of Law", name: "Department of Tax Law" },

  // Faculty of Agriculture
  { facultyName: "Faculty of Agriculture", name: "Department of Crop Science" },
  { facultyName: "Faculty of Agriculture", name: "Department of Soil Science" },
  { facultyName: "Faculty of Agriculture", name: "Department of Animal Science" },
  { facultyName: "Faculty of Agriculture", name: "Department of Agricultural Economics" },
  { facultyName: "Faculty of Agriculture", name: "Department of Agribusiness" },
  { facultyName: "Faculty of Agriculture", name: "Department of Fisheries & Aquaculture" },
  { facultyName: "Faculty of Agriculture", name: "Department of Forestry" },
  { facultyName: "Faculty of Agriculture", name: "Department of Horticulture" },
  { facultyName: "Faculty of Agriculture", name: "Department of Plant Breeding" },
  { facultyName: "Faculty of Agriculture", name: "Department of Agricultural Extension" },

  // Faculty of Education
  { facultyName: "Faculty of Education", name: "Department of Educational Management" },
  { facultyName: "Faculty of Education", name: "Department of Curriculum Studies" },
  { facultyName: "Faculty of Education", name: "Department of Early Childhood Education" },
  { facultyName: "Faculty of Education", name: "Department of Primary Education" },
  { facultyName: "Faculty of Education", name: "Department of Secondary Education" },
  { facultyName: "Faculty of Education", name: "Department of Guidance & Counselling" },
  { facultyName: "Faculty of Education", name: "Department of Special Education" },
  { facultyName: "Faculty of Education", name: "Department of Educational Psychology" },
  { facultyName: "Faculty of Education", name: "Department of Adult Education" },
  { facultyName: "Faculty of Education", name: "Department of Science Education" },

  // Faculty of Environmental Sciences
  { facultyName: "Faculty of Environmental Sciences", name: "Department of Architecture" },
  { facultyName: "Faculty of Environmental Sciences", name: "Department of Quantity Surveying" },
  { facultyName: "Faculty of Environmental Sciences", name: "Department of Building Technology" },
  { facultyName: "Faculty of Environmental Sciences", name: "Department of Estate Management" },
  { facultyName: "Faculty of Environmental Sciences", name: "Department of Surveying & Geoinformatics" },
  { facultyName: "Faculty of Environmental Sciences", name: "Department of Urban Planning" },
  { facultyName: "Faculty of Environmental Sciences", name: "Department of Environmental Management" },
  { facultyName: "Faculty of Environmental Sciences", name: "Department of Landscape Architecture" },
  { facultyName: "Faculty of Environmental Sciences", name: "Department of Interior Design" },
  { facultyName: "Faculty of Environmental Sciences", name: "Department of Construction Management" },

  // Faculty of Information & Digital Technologies
  { facultyName: "Faculty of Information & Digital Technologies", name: "Department of Information Technology" },
  { facultyName: "Faculty of Information & Digital Technologies", name: "Department of Cloud Computing" },
  { facultyName: "Faculty of Information & Digital Technologies", name: "Department of Blockchain Technology" },
  { facultyName: "Faculty of Information & Digital Technologies", name: "Department of Robotics" },
  { facultyName: "Faculty of Information & Digital Technologies", name: "Department of Internet of Things" },
  { facultyName: "Faculty of Information & Digital Technologies", name: "Department of Game Development" },
  { facultyName: "Faculty of Information & Digital Technologies", name: "Department of UI/UX Design" },
  { facultyName: "Faculty of Information & Digital Technologies", name: "Department of Digital Marketing" },
  { facultyName: "Faculty of Information & Digital Technologies", name: "Department of E-Commerce" },
  { facultyName: "Faculty of Information & Digital Technologies", name: "Department of Business Analytics" },

  // Faculty of Transport & Logistics
  { facultyName: "Faculty of Transport & Logistics", name: "Department of Transportation Management" },
  { facultyName: "Faculty of Transport & Logistics", name: "Department of Aviation Management" },
  { facultyName: "Faculty of Transport & Logistics", name: "Department of Maritime Studies" },
  { facultyName: "Faculty of Transport & Logistics", name: "Department of Railway Engineering" },
  { facultyName: "Faculty of Transport & Logistics", name: "Department of Logistics Engineering" },
  { facultyName: "Faculty of Transport & Logistics", name: "Department of Fleet Management" },
  { facultyName: "Faculty of Transport & Logistics", name: "Department of Port Management" },
  { facultyName: "Faculty of Transport & Logistics", name: "Department of Supply Chain Analytics" },

  // Faculty of Creative & Media Technologies
  { facultyName: "Faculty of Creative & Media Technologies", name: "Department of Film Production" },
  { facultyName: "Faculty of Creative & Media Technologies", name: "Department of Cinematography" },
  { facultyName: "Faculty of Creative & Media Technologies", name: "Department of Animation" },
  { facultyName: "Faculty of Creative & Media Technologies", name: "Department of Multimedia Technology" },
  { facultyName: "Faculty of Creative & Media Technologies", name: "Department of Sound Engineering" },
  { facultyName: "Faculty of Creative & Media Technologies", name: "Department of Digital Photography" },
  { facultyName: "Faculty of Creative & Media Technologies", name: "Department of Content Creation" },
  { facultyName: "Faculty of Creative & Media Technologies", name: "Department of Advertising" },

  // Faculty of Advanced Research & Innovation
  { facultyName: "Faculty of Advanced Research & Innovation", name: "Department of Nanotechnology" },
  { facultyName: "Faculty of Advanced Research & Innovation", name: "Department of Renewable Energy" },
  { facultyName: "Faculty of Advanced Research & Innovation", name: "Department of Space Science" },
  { facultyName: "Faculty of Advanced Research & Innovation", name: "Department of Climate Change Studies" },
  { facultyName: "Faculty of Advanced Research & Innovation", name: "Department of Artificial Intelligence Research" },
  { facultyName: "Faculty of Advanced Research & Innovation", name: "Department of Biotechnology Research" },
  { facultyName: "Faculty of Advanced Research & Innovation", name: "Department of Smart Systems Engineering" },
  { facultyName: "Faculty of Advanced Research & Innovation", name: "Department of Quantum Computing" },

  // Faculty of Professional Studies
  { facultyName: "Faculty of Professional Studies", name: "Department of Leadership Studies" },
  { facultyName: "Faculty of Professional Studies", name: "Department of Corporate Governance" },
  { facultyName: "Faculty of Professional Studies", name: "Department of Risk Management" },
  { facultyName: "Faculty of Professional Studies", name: "Department of Financial Technology (FinTech)" },
  { facultyName: "Faculty of Professional Studies", name: "Department of Compliance & Regulation" },
  { facultyName: "Faculty of Professional Studies", name: "Department of Business Law" },
  { facultyName: "Faculty of Professional Studies", name: "Department of Digital Transformation" },
  { facultyName: "Faculty of Professional Studies", name: "Department of Innovation Management" }
];

module.exports = {
  facultiesData,
  departmentsData
};
